use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# AuthorityWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
#
config :phoenix, :serve_endpoints, true

config :authority, AuthorityWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  load_from_system_env: true,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:authority, :vsn),
  url: [scheme: "https", host: "auth.example.com", port: 443]

# NOTE: In your secret file add:
# config :authority, AuthorityWeb.Endpoint,
#   url: [scheme: "https", host: "example.com", port: 443],
#   secret_key_base: "xyz"

config :logger, level: :info

import_config "prod.secret.exs"
